version: '3.8'

services:
  db:
    image: mysql:8.3
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: gamedb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mysqldata:

